apiVersion: v1
kind: Service
metadata:
  name: rest-app
  labels:
    app: rest-app
spec:
  type: ClusterIP
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: djan-rest
status:
  loadBalancer: {}
